services:
  - type: web
    name: perfume-stock
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: MONGO_URI
        value: "your-mongodb-connection-string"